apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
data:
  POSTGRESQL_USERNAME: <base64 encoded value>
  POSTGRESQL_PASSWORD: <base64 encoded value> 
  POSTGRESQL_DATABASE: <base64 encoded value>
  POSTGRESQL_POSTGRES_PASSWORD: <base64 encoded value>
