pipeline{
    agent{
        docker {image 'node:16-alpine'}
    }
    stages{
        stage("Test Stage"){
            steps{
                echo "Testing the pipeline"
            }
            stages{
                sh 'node --version'
            }
        }
    }
}