apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: kiali-server
    meta.helm.sh/release-namespace: istio-system
  labels:
    app: kiali
  name: kiali
  namespace: istio-system
