apiVersion: v1
kind: Secret
metadata:
  name: cluster5
  labels:
    kiali.io/multiCluster: "true"
stringData:
  cluster5: |
    apiVersion: v1
    kind: Config
    preferences: {}
    current-context: cluster5
    contexts:
    - name: cluster5
      context:
        cluster: cluster5
        user: cluster5
    users:
    - name: cluster5
      user:
        token: eyJhbGciOiJSUzI1NiIsImtpZCI6Im5qa0k2cUZ6MVM5N1RxUzJuMUFwaEJObFBUOEtCYzYxc0dyd3NjdmlwMlkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJpc3Rpby1zeXN0ZW0iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoia2lhbGktcmVtb3RlLWFjY2Vzcy10b2tlbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJraWFsaSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6Ijk1Y2I0ODc0LWI1ZmYtNDcxMS1iNGNiLTNhMDdhMTE4OWI5OCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDppc3Rpby1zeXN0ZW06a2lhbGkifQ.HZL_z0UO0rVAX0_FdKnpL4NBFFWDBjirc4L17ZYyPqsuCr2C6y-p_g3eZw0zzJH9jKmUnsrt9XrWXpwezmt4G6sZFLPkKmhSDZQHOlQlTUW0q_x7HbZYXSYWiXXWn_2oVtBzLpLN622eZI9b6waQOLCenPcCH6xI7o3rhKrfIla6rZwDe7XrvbDzLOtNtPuso9zp64Q43nv2nJo4AuenRdx8rVL8-ZS1edtS6iCCV5cTZzG7ZPX5uPt-MVgJbFOA-s5EY-tScOFeXSYxAHh59MISKpwhz9WDTl3h2TthYVE0wT7rSqAN0bKlff3ZDZXb0ObY-XA4tx3wCynwK2LzPg
    clusters:
    - name: cluster5
      cluster:
        server: https://172.25.157.117:6443
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJRzJmdldtSmQrZEV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBM01Ea3dNakU1TXpGYUZ3MHpOVEEzTURjd01qSTBNekZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURLTm16WlpGUUlJM21uOGV5dHBlZmd4RWhCTWU3ZGVOWDBRWUtOQ3luUWNuUlZiajExb2xRRVhQQVcKeUxOMUhlSmV4dmZJRmQvNHhERm5HWDVGZDdrYlBhZmhMQ3YrVVF0SDFvZUxHZXFoV0U1OFI1ck1yZjREMGg2agpTckw2Y2kwbWdYdWdXY2V0c0xkTC81aUZJV3JrQ20wTkU1OWpzRi9LWGtFTC92VHg5dGlUK010cDZXOW5MU2pVCnUzTUY4UW9BajVUSzBjNG1vbjRFRGNIZkNyZ1NwckdQSTRxcmoxMitWeEpGVjNWdEpiTThYQkR6Y2RhV1BGNkUKT2VDNWFXdTYzRlU1TUZibHZaNy9JdWZOdDh0b29FY0hmNjlUSHdVYTBDWGFzZjFMWElaMzdHcUFmVW44ZWVTcgpLRGZMK0dXU3laVWNGd0NMcXkrMjZzZW84UEI5QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTUXhtVlBRY2xhMmdrN3RMUVVrZEpGdTZDbjR6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQysxRmhVazJYWAp2Wk9HMVV5MHhERllUSWsyc3g5S3lyZXl1N1dEbUZnZitzaUxtRkhoZ2tRRSs0cEdzKzMrMG9FK3kzQVkzd01kClZTSHVDbWl5bS90NXJKK3dJVytpdjJFUW1EUHRWVzRJRGhNbHFnV2FEZ21tcitqUjd4Tk5PV0lmb0dYTW5rZTIKdHlkQ3ZKbXp1MUxOc1FpYTdkaUZDZCtRRHowTVhaNDBCNFF3ZDdIdFpWL3BDc3lQNFAwK2xncVgzN2dNbndzcgpyOUdJMVdEeGhYZ2VjWG5XdUV1VDRCbkFRUUtxUE5xWlhQUlFsNk5iWGxxYmcrUnRTRzhyamZ3Q0RlVW5GT1JSCnkvVm5POXZwWFJmM21Sd25yN3B3ampTdEJMZXZpcSt0dmFQNXMzZjlPcmtkcHM0ZzB5TEhsb3BOaUhkSjY0VVYKOStRQ3dUMEl2MmhzCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K 
