apiVersion: v1
kind: Secret
metadata:
  annotations:
    networking.istio.io/cluster: cluster2
  creationTimestamp: null
  labels:
    istio/multiCluster: "true"
  name: istio-remote-secret-cluster
  namespace: istio-system
stringData:
  cluster2: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJTW5zSlA2M0NOK0l3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBME1UWXdPRFEwTVRCYUZ3MHpOVEEwTVRRd09EUTVNVEJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUM2UlR4T3QyV2dMWE9VYUpURDhza2JsTkhMMWU5QVdWQkt0NjczUlFxaXBaUmdnaWh3c2xtaXBDbmkKdjdSMEVSZ2RmQmJlTnBESjl2anBrZEdkNS92SVhSUXRCaFFWN3ZjMW00T1k4UmVvdlB1Zlcxb0x5c09udEs0VApQM0FhUGtQWHEwWmg0ZUxHVkEyb2pDcHloSUJYb04vV0s1L0RXVFduZFpKcFlqVVJyOGR6b1VRYmtidjhCZnVLCjlnRTExWXYvSnptQ3ovbUVnT29KSjZHalliam9WQlBzVmhESTlaZ1RMaE5XWWd2MXcxVGxqNElFUUowZXVLcUQKRU9nR0drQ0tSZnd0QWhCSjk0MnliOG5hbWplSHVieVJuTmhoZDlCR0ExS1NaTnM3TE1UVHdhSnBmbDUrUm9TZAp1YXNJQ3RvOWtLUG9zVWoya1B0UUxmaEFlYlR4QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTNVQvano0RGRSM2EyY3FGL1BTaVUxeHBrMDREQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQjhQSysxMk1rcgphSW42NE5VS1FsbkN3YnFzNjV5U2tXc3BGTU5TTVpiY1BVZlhPMU05MnROanFkL1B3OHZvc0w3KzhHRjNxaC9NCmcrNHk4U0ZTNXUzUUxjLzZZWmJ6ek9lYzZNRjZ0Vm9XdjdRL1FHc3ZxMmtHRWpsSWZLekZmQXNmd1NRM2pXc3EKRWtYQzAyTjlZVzJ2RHZjczNkVEphNElRcEZoY0tTamdIbXBEWVE1MGlHVStnWmplbU1EdVl6UlJUSEZrekdHQgp3TGo5WjUyWkhveGVmV21pMHAza0FZUkZkVC85di9vK3ROeExzRDYxYXJKZG5SNzE1b2p0c3M5dmR1QkFWeVFuCjc4ZjloSVVHamdsRlN1YWp5L3NDbVJrWGp6cmdlU1JxNGU2NThMZUkzOE5FVVZjRTQwOWNXRGhXdVdSQUs5MzQKTktDSTNXYUZXaVZ6Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        server: https://172.25.157.192:6443
      name: cluster2
    contexts:
    - context:
        cluster: cluster2
        user: cluster2
      name: cluster2
    current-context: cluster2
    kind: Config
    preferences: {}
    users:
    - name: cluster2
      user:
        token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImZwTWdkNjVWNFU2NmhYRmVoTmhlZWJTQ1J6b0RSU0NNcUtBOU1HU0p4cUEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJpc3Rpby1zeXN0ZW0iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiaXN0aW8tcmVtb3RlLWFjY2Vzcy10b2tlbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJpc3Rpby1yZW1vdGUtYWNjZXNzIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYTk5YWNkZDYtODBiMS00MjAwLThkNTktYjJmYTcxMjc0YmEyIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmlzdGlvLXN5c3RlbTppc3Rpby1yZW1vdGUtYWNjZXNzIn0.eOEHSc8wNYfkHmqmSHhRdEJOk6yUdkLB4yRQMt-5_scLUxn0YTWoxFlwGzTb48jAzNZN9Cj3Vf1WV5hWwGFet4ZzT_gPRWJC6qi42ZGQxjTVnAUPJoIh0KAFBRyAH1hPdhFxlYSmL8aXj5WmNOCgJgyznEscIsvvTSZfYjNM3lgU_HydR-4jWhp5EyFY0xJ2esTXEmrRyB9PWbx8FSs07SPgvlK3JpcaA2RDjvYgO6H8GmNZhRE4lJ1YdeBlgr4FjN8VTRYXjv6HwzeS4kwTLnNBASuH2Fkj3ziDoq0pIp1NB4N-6bIGv6k86ijeq_q8lrkKOlgz22quYzjB5uANyA
