clusterName: "teleport.test.qzz.io"
proxyListenerMode: multiplex
acme: false
log:
  level: DEBUG
tls:
  existingSecretName: teleport-tls-teleport.test.qzz.io 
auth:
  # Bật auth service
  enabled: true
  teleportConfig:
    auth_service:
      authentication:
        second_factors: ["otp"]
    proxy_service:
      enabled: true
      web_listen_addr: "0.0.0.0:443"
      public_addr: "teleport.thalt.qzz.io:443"
    app_service:
      enabled: true
      # apps:
      #   - name: "test"
      #     uri: "http://nginx-test.web.svc.cluster.local:80"
      #     public_addr: "test.test.qzz.io"
      #     insecure_skip_verify: true
      debug_app: true
    ssh_service:
      enabled: true
    teleport:
      storage:
        type: postgres
        # Cấu hình PostgreSQL connection - External Database
        conn_string: "postgres://teleport:teleport@host:port/teleport?sslmode=disable"
        audit_events_uri:
          - postgres://teleport:teleport@host:port/teleport?sslmode=disable
        audit_sessions_uri: "s3://s3-teleport/teleport-records?endpoint=http://s3-hcm.test.vn&region=hcm&insecure=true&disablesse=true&disableChecksum=true"
proxy:
  teleportConfig:
    proxy_service:
      public_addr: "teleport.test.qzz.io:443"
extraEnv:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: teleport-s3-credentials
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: teleport-s3-credentials
          key: AWS_SECRET_ACCESS_KEY
    # Tun off checksum
    - name: AWS_REQUEST_CHECKSUM_CALCULATION
      value: "when_required"
    - name: AWS_RESPONSE_CHECKSUM_VALIDATION
      value: "when_required"
highAvailability:
  replicaCount: 2
image: vcr.infiniband.vn/teleport/teleport-5
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    memory: "256Mi"
persistence:
  enabled: false
service:
    type: LoadBalancer
    spec:
      externalIPs:
        - <IP-External>