teleport:
  data_dir: /var/lib/teleport
  storage:
    type: postgres
    conn_string: "postgres://teleport:teleport@host:port/teleport?sslmode=disable"
    audit_events_uri:
      - "postgres://teleport:teleport@host:port/teleport?sslmode=disable"
    audit_sessions_uri: "s3://s3-teleport/teleport-records?endpoint=http://s3-hcm.test.vn&region=hcm&insecure=true&disablesse=true&disableChecksum=true"
auth_service:
  cluster_name: teleport.test.qzz.io
  enabled: true
  authentication:
    second_factors: ["otp"]
proxy_service:
  enabled: true
  web_listen_addr: "0.0.0.0:443"
  public_addr: "teleport.test.qzz.io:443"
  https_keypairs:
  - cert_file: /etc/letsencrypt/live/teleport.test.qzz.io/fullchain.pem
    key_file: /etc/letsencrypt/live/teleport.test.qzz.io/privkey.pem
  https_keypairs_reload_interval: 0s
app_service:
  enabled: true
  debug_app: true
#  apps:
#    - name: "test"
#      uri: "http://nginx-test.web.svc.cluster.local:80"
#      public_addr: "test.test.qzz.io"
#      insecure_skip_verify: true
ssh_service:
  enabled: true