apiVersion: v1
kind: ConfigMap
metadata:
  name: teleport-config
  namespace: teleport
data:
  teleport.yaml: |
    version: v3
    teleport:
      data_dir: /var/lib/teleport
      storage:
        type: postgres
        conn_string: "postgres://teleport:teleport@host:port/teleport?sslmode=disable"
        audit_events_uri:
          - "postgres://teleport:teleport@host:port/teleport?sslmode=disable"
        audit_sessions_uri: "s3://s3-teleport/teleport-records?endpoint=http://s3-hcm.test.vn&region=hcm&insecure=true&disablesse=true&disableChecksum=true"
      ca_pin: ''
      advertise_ip: teleport.test.qzz.io
      diag_addr: 0.0.0.0:3000
    auth_service:
      cluster_name: teleport-test
      enabled: true
      proxy_listener_mode: multiplex
      listen_addr: 0.0.0.0:3025
      proxy_protocol: on
      routing_strategy: most_recent
      authentication:
        second_factors: ["otp"]
    proxy_service:
      enabled: true
      web_listen_addr: "0.0.0.0:443"
      public_addr: "teleport.test.qzz.io"
      trust_x_forwarded_for: true
    app_service:
      enabled: true
      debug_app: true
      # apps:
      #  - name: "test"
      #    uri: "http://nginx-test.web.svc.cluster.local:80"
      #    public_addr: "test.test.qzz.io"
      #    insecure_skip_verify: true
      #    labels:
      #     env: "test"
      #  - name: "minio"
      #    uri: "http://minio-service.minio.svc.cluster.local:9001"
      #    public_addr: "minio.test.qzz.io"
      #    insecure_skip_verify: true
      #    labels:
      #     env: "test"
      #     service: "minio"
    ssh_service:
      enabled: true