apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  namespace: thalt-jk
spec:
  storageClassName: "csi-rbd-sc-hci01-pvc"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
