apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-sync-webhook
  namespace: istio-system
---
apiVersion: v1
kind: Secret
metadata:
 name: istio-sync-webhook-access-token
 namespace: istio-system
 annotations:
   kubernetes.io/service-account.name: istio-sync-webhook
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-sync-webhook
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["create", "get", "list", "watch", "update", "delete"]
- apiGroups: ["networking.istio.io", "extensions.istio.io", "security.istio.io", "telemetry.istio.io"]
  resources: ["wasmplugins", "destinationrules", "envoyfilters", "gateways", "proxyconfigs", "serviceentries", "sidecars", "virtualservices", "workloadentries", "workloadgroups", "authorizationpolicies", "peerauthentications", "requestauthentications", "telemetries"]
  verbs: ["create", "get", "list", "watch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istio-sync-webhook
subjects:
- kind: ServiceAccount
  name: istio-sync-webhook
  namespace: istio-system
roleRef:
  kind: ClusterRole
  name: istio-sync-webhook
  apiGroup: rbac.authorization.k8s.io
