apiVersion: v1
kind: Service
metadata:
  name: istio-sync-webhook
  namespace: istio-system
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: istio-sync-webhook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-sync-webhook
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istio-sync-webhook
  template:
    metadata:
      labels:
        app: istio-sync-webhook
    spec:
      containers:
      - name: webhook
        image: thanhtha/istio-sync-webhook:v11
        volumeMounts:
        - name: certs
          mountPath: /certs
          readOnly: true
        env:
        - name: PRIMARY_CLUSTER_API
          value: "https://172.25.157.186:6443" # Thay bằng API server của primary cluster
        - name: PRIMARY_CLUSTER_TOKEN
          valueFrom:
            secretKeyRef:
              name: istio-sync-webhook-secret
              key: token
      volumes:
      - name: certs
        secret:
          secretName: istio-sync-webhook-certs
---
apiVersion: v1
kind: Secret
metadata:
  name: istio-sync-webhook-certs
  namespace: istio-system
type: Opaque
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURoVENDQW0yZ0F3SUJBZ0lVVkRFK01CRmdJTS9BazNPbytxWDc3Q3lTMWZNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0lERWVNQndHQTFVRUF3d1ZhWE4wYVc4dGMzbHVZeTEzWldKb2IyOXJMV05oTUI0WERUSTFNRGN6TVRFeApOVE14TWxvWERUSTJNRGN6TVRFeE5UTXhNbG93TGpFc01Db0dBMVVFQXd3amFYTjBhVzh0YzNsdVl5MTNaV0pvCmIyOXJMbWx6ZEdsdkxYTjVjM1JsYlM1emRtTXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUsKQW9JQkFRREdRVFR6SGhGeFJTVndZNGVMMTZtR0FuNDFvL25lcjlHeGhJak9uRUVWcS9vRUZ3eVdQdVk3TThZZgprakUxcUhsVHdLQjRJekRub3VWYktNZEhURytzbzUvdkJId3pTcnZGMHkrbEJjWTVYY01BL0g3OUxrZk1LRFVKCkZuUDlMeUpRY3BLbmMyUnVDTjgzWVFqVUhvNmltWXhnV25RQUNKcGJ0RlBOTG1pM0hpZml0S3p3ejc5SFgzNWgKalZRRit1S1RYMDVaKzIxRXJQRFcrUFY1Yi90TnRBY0dFSCtBa3lvQXBtSU9taGhZbHdqcEIxRWFjTGlaVFVQZgo1Wm5lT3hudjlDL1A1MzVwVSt6dFRsQ3l2Y0p6eGxMTG5KWGZKZlJKSkt3VU1DYklxNCtwVzNGMGNIVUI3eXZmClVjU3JyWFNsMmZsaTdqN1U2TE1xMGg3T1F5cERBZ01CQUFHamdhZ3dnYVV3WXdZRFZSMFJCRnd3V29JamFYTjAKYVc4dGMzbHVZeTEzWldKb2IyOXJMbWx6ZEdsdkxYTjVjM1JsYlM1emRtT0NIMmx6ZEdsdkxYTjVibU10ZDJWaQphRzl2YXk1cGMzUnBieTF6ZVhOMFpXMkNFbWx6ZEdsdkxYTjVibU10ZDJWaWFHOXZhekFkQmdOVkhRNEVGZ1FVClVpU2dBaEtjQUFZb2FvelhDREt6WklCVzV2c3dId1lEVlIwakJCZ3dGb0FVSzZsOUZ2L1lRRUpBdEc2a2g0bGgKTXREUmllVXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQ3ZtRCtiOHBxZWtFS0FudXgxaEJ1SVVTNE9kZlM4UQpvaUMxMXdEQWFJVmNHeCsyNE4xWWNMOTB1NzNxc1A2cGQzY0h3MU5lNEY5cHlvYWRoVmpZbkpsTm5lUWtOQTJNCktsblV4NW45aTVjdFFjNE9JZTBmcmNPRFI0RDZZZjRzaFh1YWVjRFFYbnppQ3BCd0J0NjN1S3hyNGdXcWNIS3YKa1pPUG0xU2xRQUZkazFDNXVsQk0xVHY0eWQ2bmJNNVpUc0l1bkZ5d0QxVm5lNHUxeHNqOTlVdkxpYzl2enBMaQp1RGlTcjBxc0thTTRNWnp2MG5uM20yVFpkVWxlRDRuOVA5TndNRkd1VXowMUVtdTZjMXdFdGFyaEJkSzNOdkVKCi9Ea04zWVdmUUZ4UVhCQ0dGUGFRZEQwOFVkaWp4dG9pNXJETFpNZUtERElyWUpLckxNWTN4bGs9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRREdRVFR6SGhGeFJTVncKWTRlTDE2bUdBbjQxby9uZXI5R3hoSWpPbkVFVnEvb0VGd3lXUHVZN004WWZrakUxcUhsVHdLQjRJekRub3VWYgpLTWRIVEcrc281L3ZCSHd6U3J2RjB5K2xCY1k1WGNNQS9INzlMa2ZNS0RVSkZuUDlMeUpRY3BLbmMyUnVDTjgzCllRalVIbzZpbVl4Z1duUUFDSnBidEZQTkxtaTNIaWZpdEt6d3o3OUhYMzVoalZRRit1S1RYMDVaKzIxRXJQRFcKK1BWNWIvdE50QWNHRUgrQWt5b0FwbUlPbWhoWWx3anBCMUVhY0xpWlRVUGY1Wm5lT3hudjlDL1A1MzVwVSt6dApUbEN5dmNKenhsTExuSlhmSmZSSkpLd1VNQ2JJcTQrcFczRjBjSFVCN3l2ZlVjU3JyWFNsMmZsaTdqN1U2TE1xCjBoN09ReXBEQWdNQkFBRUNnZ0VBWUJXSlJvemJra1NiWFFsM3o1QkJvbWZCNkZobENRYTRQK3RHYkxBeElRSTkKQlU5d2M3N2ZVWEVKeEJKVDFEZ25PUzZoOXlmREUzaVE1U254enYzZUg5TWJkN2w2UWxlbGdyNlVHRXdnb252dApQeVNnblM4WmIvcEtuZkZxWEpwRDdLNWlvbEpjS2JJV0VONXY2M0kxMmR0R1BBcUtydHQ4aUJaeENQL0ZrMzFvCi9kZFk2Q3I4STBMempzL1pmQUFGUlBCU2UvMXkvaE56dHdKL2RTSmNWS1JCTXFEb0Z1UTZjMVl1MFd0K0IwZXoKVE5YNWtGWXN1RjdLbk5qdm1IRVMxdFlITUFXMWdrNG5oVWJpaEVqZ2Q3UVgwNXBrbGo0RkptelJSVk14Z2ZEOAphV3pUaEVtdUtxU3BDNEF0cGZDak1uUEM2cVVtS3p0MDZwSEt0TWNIOVFLQmdRRHBxWit0VHFzb1lQckRUWlM5Cnhxc1JSdStYK3dmQ1dkY29aeFdWZDBjUGYyeThyTWp3NlpVNFdUYUt3OG5hNzgzMnlJZlBTa0R5ckNoWU1NZHkKU0FyaklFMGt1Q21XOEFSNzY5aCtiOXBCQjIvWUZqNTB3a2N5b3NpWXJWVWIvY0hkZEhSR0NEQzhjQURVSWtWMQpYOEhqczU3ZC9iNjU5emcwQjVJRmpDVUhud0tCZ1FEWk5RMnNtZHF4ejBvTzZnUXkzdmIwdGJCV0xiRFU3TVlmCjJhS2trbjhkL0hidTdWcUtSb0VKeHN6elozQjlXWVcyMldWckV1K2xEZE9pSzFqd2U1QzlnZS9Rcy9aTFloM3IKVll1SlFRczU4YXpJbSt2TGxiMEUxMGw4L3hETFlIdW5EbjMxQzk0MXFmUm4vbXRpM203c2pLTWZ3cW14L1dWUQpQYzVKcTBTcTNRS0JnSFNnVkhIRlRVckhOUUtjUzN4NWw5TDB6QXZZb1NQUmdjSEp5ZzBqVHRXZWJXQ3pBVXkxCjJlUVpLMDhSc0VQVjQ4Q2trSnpYWEJtRDhsTXFiYkpONFJsQ2V4Nnp5UlpzVUdDbDlCWVBzQ2s3RkFrUCtUWi8KN2RlSlJvUm1KNC9rRllwNllMcS94Y3VZUCtHaUJYY3pSMnhtc0FudlorNGNSZkk2UVJrQnZVM1RBb0dBT241WQpGV0JGamRibCtjZzVvejE2UWdKZjM0VmtkcUxnNUJqbS9PemF3TWVKZStSOW1ubE1MTWJWME1MTmYyUkpaeWw2CmIzQmxDdzBETGt3QUlwc1VLb1RBZ1hMRlpCMmpNd29SanIvdWR3ZEhZYXJqd0NxdUFZeThwS1hIN3cwbm42QisKZVN4ZUJoT2oxeEdqOTdjeEpoRGxxUnJ5T2hXa1lBeVU3aS9xU1IwQ2dZRUFoTDl0ODhUZWo5YjQzUVkrREpUTQowbTY5bVc3Q2Y0alBFRTBFdTduVDhIQ285a3gyYk1qTkdkamVwejgySkdRenl4V1JTaWRibkFYNkVzRkZ5MmFGCmQ2dEpIUnBDbTVaT1lkTlE0eGFTcEpJUGNKYmYwMVlIYXJuRDZ0ZEVCYjFwV2s3c0ptZCtxb1VPZkZoam03QlEKR2pzZXpmakJhQ1oxOTJ2ZjZPa0xWdm89Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
---
apiVersion: v1
kind: Secret
metadata:
  name: istio-sync-webhook-secret
  namespace: istio-system
type: Opaque
data:
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklsRjFaRVJJVGtaVWFVOVhUVzAyVVV0dFlrTkJTMDlXVmpGb1NVWkhjRVJMY1V0TlFqUTVOMnBXYm1NaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUpwYzNScGJ5MXplWE4wWlcwaUxDSnJkV0psY201bGRHVnpMbWx2TDNObGNuWnBZMlZoWTJOdmRXNTBMM05sWTNKbGRDNXVZVzFsSWpvaWFYTjBhVzh0YzNsdVl5MTNaV0pvYjI5ckxXRmpZMlZ6Y3kxMGIydGxiaUlzSW10MVltVnlibVYwWlhNdWFXOHZjMlZ5ZG1salpXRmpZMjkxYm5RdmMyVnlkbWxqWlMxaFkyTnZkVzUwTG01aGJXVWlPaUpwYzNScGJ5MXplVzVqTFhkbFltaHZiMnNpTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxjblpwWTJVdFlXTmpiM1Z1ZEM1MWFXUWlPaUl6TWpka056WmtNaTB4T1daakxUUTVaamt0WW1VNE1DMHpPR1UyWXpZM1l6ZG1ZVFVpTENKemRXSWlPaUp6ZVhOMFpXMDZjMlZ5ZG1salpXRmpZMjkxYm5RNmFYTjBhVzh0YzNsemRHVnRPbWx6ZEdsdkxYTjVibU10ZDJWaWFHOXZheUo5LkRCRHItUWZPNnRkYVhqWE1zWUgwWUh5Rl8tSHF5VWd5c3Z6NE5SQTI4cGtNeEdGZkFWZkZFaDlhOTQ0T2VCQnNxaGxaQVZaMHY5cmJtQ0hsTVVidU5zcmdfWGJwZklTdTl0dDdRUUd0dDdTWVdvdUw3bUp4X1VoNmdNX2RPcllGUHVkaFpJZ0g1Sk1QU1J0T2JNQTJFcHF5SVhTOFRxSlpzaXNMN25LaWJuM2xMLXZGTTd5WFlJNkg5WC1oRWJESmJxN0NGV2FVS3l4TWhjTmR0VzVmTXpNZDhFX2Q4UDJuM3VhS1Z3MWQ4bmlfUHdQUHMyZ00tTzRkOWZqd25fN2Z0cVdKaWpNLXBjRXhuMkhiN2dXcHU2OXIwZ1BoWjZEUkR3VVpQZ2R2SWU1a2RZWDNLNXVJLWV1MUpVSmpNUzNzODAweUdmNEFncElxRERRZkZKMVNhdw==