{
 "title": "iPerf3  Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Sent Bandwith",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iperf",
     "query": "SELECT  \"bandwidth_sent\" FROM \"iperf\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "bandwidth_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Received Bandwith",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "query": "SELECT \"bandwidth_received\"  FROM \"iperf\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Bandwith",
   "type": "barchart",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "query": "SELECT \"bandwidth_received\", \"bandwidth_sent\" FROM \"iperf\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "RTT",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "query": "SELECT \"max_rtt\", \"mean_rtt\", \"min_rtt\"  FROM \"iperf\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Retransmits",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "query": "SELECT \"retransmits\" FROM \"iperf\" WHERE $timeFilter"
    }
   ]
  }
 ]
}